networks:
  bridge:
    driver: bridge    

services:
  xray:
    container_name: xray
    image: ghcr.io/xtls/xray-core:25.10.15
    networks:
      - bridge
    #build: xray_container/.
    volumes:    
      - ./xray:/etc/xray
      - ./certbot-etc:/etc/letsencrypt/
    depends_on:
      xray_configurator: 
        condition: service_completed_successfully
    ports:
      - "80:80"
      - "443:443"
      
  xray_configurator:
    container_name: xray_configurator
    build: xray_configurator/.
    environment:
      - SNI=${DOMAIN}
      - NAME=KYZYLYK
      - USERCOUNT=50
    env_file: .env
    networks:
      - bridge
    volumes:    
      - ./xray:/etc/xray
      - ./connection:/connection

  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    networks:
      - bridge
    env_file: .env
    volumes:
      - ./nginx/sni.conf.template:/etc/nginx/templates/sni.conf.template
      - ./nginx/site:/var/www/html/site
      - ./certbot-etc:/etc/letsencrypt/
