networks:
  bridge:
    driver: bridge    

services:
  xray:
    container_name: xray
    restart: unless-stopped
    image: ghcr.io/xtls/xray-core:25.10.15
    networks:
      - bridge
    user: root
    volumes:    
      - ./xray:/usr/local/etc/xray
      - ./certbot-etc:/etc/letsencrypt/
    depends_on:
      xray_configurator: 
        condition: service_completed_successfully
    ports:
      - "80:80"
      - "443:443"
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    logging:
      driver: 'json-file'
      options:
        max-size: '30m'
        max-file: '5'
        
  xray_configurator:
    container_name: xray_configurator
    build: xray_configurator/.
    environment:
      - SNI=${DOMAIN}
      - NAME=${NAME}
      - USERCOUNT=${USERCOUNT}
    env_file: .env
    networks:
      - bridge
    volumes:    
      - ./xray:/etc/xray
      - ./connection:/connection

  xray-connection-logger:
    build: connection_logger/.
    container_name: xray-connection-logger
    volumes:
      - ./logs:/logs
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      XRAY_CONTAINER: xray
      POLL_INTERVAL: 1
      DISCONNECT_TIMEOUT: 15
    restart: unless-stopped
    networks:
      - bridge
    depends_on:
      - xray
    logging:
      driver: 'json-file'
      options:
        max-size: '30m'
        max-file: '5'

  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    networks:
      - bridge
    env_file: .env
    volumes:
      - ./nginx/sni.conf.template:/etc/nginx/templates/sni.conf.template
      - ./nginx/site:/var/www/html/site
      - ./certbot-etc:/etc/letsencrypt/
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    logging:
      driver: 'json-file'
      options:
        max-size: '30m'
        max-file: '5'
